DROP TABLE EMPLOYE;
DROP TABLE EMPLOYEE;
DROP TABLE REIM;
DROP SEQUENCE SQ_EMPLOYEE_PK;
DROP SEQUENCE SQ_REIM_PK;

CREATE TABLE EMPLOYEE (
    EMP_ID INTEGER PRIMARY KEY,
    EMP_USER VARCHAR2(100) UNIQUE NOT NULL,
    EMP_PASS VARCHAR2(100) NOT NULL,
    MAN_ID   INTEGER
);

CREATE TABLE REIM (
    REIM_ID INTEGER PRIMARY KEY,
    EMP_ID INTEGER,  --fk
    BALANCE NUMBER,
    DETAILS VARCHAR(200),
    REIM_CHECK INTEGER DEFAULT 2,   --0 FOR DENIED 1 FOR APPROVED 2 for pending
    MANAGE_ID INTEGER ,             --0 for no 1 for yes if employee is managed
    MANAGER_RESOLVED_ID INTEGER -- manager that resolved request id number
);
---ALTER TABLE FK
ALTER TABLE REIM
ADD CONSTRAINT FK_EMP_ID
FOREIGN KEY (EMP_ID) REFERENCES EMPLOYEE(EMP_ID);

--SEQUENCES
CREATE SEQUENCE SQ_EMPLOYEE_PK
START WITH 1
INCREMENT BY 1;
/

CREATE SEQUENCE SQ_REIM_PK
START WITH 1
INCREMENT BY 1;
/
--TRIGGERS
CREATE OR REPLACE TRIGGER TR_INSERT_EMPLOYE
BEFORE INSERT ON EMPLOYEE
FOR EACH ROW
BEGIN
    SELECT SQ_EMPLOYEE_PK.NEXTVAL INTO :NEW.EMP_ID FROM DUAL;
END;
/

CREATE OR REPLACE TRIGGER TR_INSERT_REIM
BEFORE INSERT ON REIM
FOR EACH ROW
BEGIN
    SELECT SQ_REIM_PK.NEXTVAL INTO :NEW.REIM_ID FROM DUAL;
END;
/
--TESTING
INSERT INTO EMPLOYEE(EMP_USER,EMP_PASS,MAN_ID) VALUES ('PRAC','PRAC',0);

INSERT INTO REIM (EMP_ID,BALANCE,DETAILS,REIM_CHECK) VALUES (1,20,'Bus Fare', 0);

INSERT ALL
INTO REIM (EMP_ID,BALANCE,DETAILS,REIM_CHECK) VALUES (1,20, 0)
INTO REIM (EMP_ID,BALANCE,REIM_CHECK) VALUES (2,2000, 0)
INTO REIM (EMP_ID,BALANCE,REIM_CHECK) VALUES (3,1000, 0)
SELECT * FROM DUAL;
/

INSERT ALL
INTO EMPLOYEE(EMP_USER, EMP_PASS, MAN_ID)
VALUES ('TEST', 'TEST', 0)
INTO EMPLOYEE(EMP_USER, EMP_PASS, MAN_ID)
VALUES ('TEST2', 'TEST2', 1)
INTO EMPLOYEE(EMP_USER, EMP_PASS, MAN_ID)
VALUES ('TEST3', 'TEST3', 1)
SELECT * FROM DUAL;
/

UPDATE EMPLOYEE SET EMP_USER = bb, EMP_PASS = bb WHERE EMP_ID = 2;

INSERT INTO REIM (EMP_ID,BALANCE,DETAILS) VALUES (1,100,'bus');

SELECT * FROM REIM WHERE EMP_ID = 2;

SELECT * FROM REIM WHERE EMP_ID = 2 AND REIM_CHECK = 1;

SELECT * FROM REIM WHERE REIM_CHECK = 0 OR REIM_CHECK = 1 AND EMP_ID != 3;

SELECT * FROM REIM WHERE EMP_ID = 2 AND MANAGE_ID = 1;

SELECT * FROM REIM WHERE MANAGE_ID = 1 AND REIM_CHECK = 2 AND EMP_ID != 3;